FROM python:3.11-slim

WORKDIR /app

COPY requirements.streamlit.txt .
RUN pip install -r requirements.streamlit.txt

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
